# Configuración de Air
root = "."  # Directorio raíz del proyecto
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe cmd/api/main.go && tmp/main.exe"
  bin = "tmp/main.exe"
  full_bin = "tmp/main.exe"

# Ignorar archivos innecesarios
[watcher]
  dirs = ["cmd/api", "internal"]
  ignore_dirs = ["tmp", "vendor", "node_modules"]
  extensions = ["go", "html", "env"]

# Configuración de logs
[log]
  time = true
